---
- name: "ensure postgresql cluster directories"
  ansible.builtin.file:
    path: "{{ postgresql_cluster_directory }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    state: "directory"
    mode: "0750"
  loop:
    - "{{ postgresql_cluster_configuration_directory }}"
    - "{{ postgresql_cluster_data_directory }}"
  loop_control:
    loop_var: "postgresql_cluster_directory"
  become: true
