---
- name: "ensure postgresql"
  block:
    - name: "ensure postgresql prerequisites"
      ansible.builtin.import_tasks: "prerequisites.yml"
    - name: "ensure postgresql environment"
      ansible.builtin.import_tasks: "environment.yml"
    - name: "ensure postgresql repository"
      ansible.builtin.import_tasks: "repository.yml"
    - name: "ensure postgresql packages"
      ansible.builtin.import_tasks: "packages.yml"
    - name: "ensure postgresql directories"
      ansible.builtin.import_tasks: "directories.yml"
    - name: "ensure postgresql postgresql.conf"
      ansible.builtin.import_tasks: "postgresql.conf.yml"
    - name: "ensure postgresql pg_hba.conf"
      ansible.builtin.import_tasks: "pg_hba.conf.yml"
    - name: "ensure postgresql pg_ident.conf"
      ansible.builtin.import_tasks: "pg_ident.conf.yml"
    - name: "ensure postgresql systemd service"
      ansible.builtin.import_tasks: "systemd_service.yml"
  tags:
    - "postgresql"
