---
- name: "ensure pg_hba.conf"
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgresql_hba_file }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0640"
  become: true
  register: "postgresql_pg_hba_conf"
