---
- name: "ensure postgresql.conf"
  ansible.builtin.template:
    src: "postgresql.conf.j2"
    dest: "{{ postgresql_config_file }}"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "0640"
  become: true
  register: "postgresql_postgresql_conf"
