---
- name: "ensure {{ postgresql_service_name }} systemd service"
  ansible.builtin.include_role:
    name: "damex.systemd.systemd_service"
  vars:
    systemd_service_name: "{{ postgresql_service_name }}"
    systemd_service_reload_on: "{{ postgresql_pg_hba_conf.changed }}"
    systemd_service_restart_on: "{{ postgresql_postgresql_conf.changed }}"
