---
namespace: "damex"
name: "postgresql"
version: "0.1.0"
readme: "README.md"
authors:
  - "Roman Kuzmitskii <damex.pp@icloud.com>"
license_file: "LICENSE"
tags:
  - "postgresql"
repository: "https://github.com/damex/ansible-collections-postgresql"
