---
namespace: "damex"
name: "postgresql"
version: "0.2.3"
readme: "README.md"
authors:
  - "Roman Kuzmitskii <damex.pp@icloud.com>"
dependencies:
  "damex.apt": "*"
  "damex.systemd": "*"
license_file: "LICENSE"
tags:
  - "postgresql"
repository: "https://github.com/damex/ansible-collections-postgresql"
